# @package _global_
model:
  model: ${oc.env:WW_MODEL_SEARCH_AGENT}
toolkits:
  query_decomposer:
    name: query_decomposer
    config:
      num_sub_queries: 3
    config_llm:
      model: ${oc.env:WW_SEARCH_DECOMPOSER_MODEL}
      base_url: ${oc.env:WW_SEARCH_TOOL_BASE_URL}
      api_key: ${oc.env:WW_SEARCH_TOOL_API_KEY}
  web_searcher:
    name: web_searcher
    config: 
      num_result: 3
      max_concurrent_searches: 5
      summary_token_limit: 1_000
    config_llm: 
      model: ${oc.env:WW_SEARCH_SEARCHER_MODEL}
      base_url: ${oc.env:WW_SEARCH_TOOL_BASE_URL}
      api_key: ${oc.env:WW_SEARCH_TOOL_API_KEY}
  summarizer:
    name: summarizer
    config: 
      max_chars: 20_000
    config_llm: 
      model: ${oc.env:WW_SEARCH_SUMMARIZER_MODEL}
      base_url: ${oc.env:WW_SEARCH_TOOL_BASE_URL}
      api_key: ${oc.env:WW_SEARCH_TOOL_API_KEY}
