# --------------------------------
# Agent Config v0.1
# --------------------------------
type: simple
model:
  api_key: ${oc.env:UTU_API_KEY}
  base_url: ${oc.env:UTU_BASE_URL}
  model: ${oc.env:UTU_MODEL_AGENT}
# model_settings:
#   parallel_tool_calls: false
toolkits:
  search: 
    name: search
    mode: builtin
    activated_tools: null
    config: {
      "summary_token_limit": 1_000,
    }
    config_llm: {"model": "${oc.env:UTU_TOOL_MODEL}", "api_key": "${oc.env:UTU_API_KEY}", "base_url": "${oc.env:UTU_BASE_URL}"}
# agent: # will be overwritten during rollout
