site_name: uTu-agent
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Toggle to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Toggle to light mode
      primary: deep purple
      accent: purple
  features:
    # Allows copying code blocks
    - content.code.copy
    # Allows selecting code blocks
    - content.code.select
    # Shows the current path in the sidebar
    - navigation.path
    # Shows sections in the sidebar
    - navigation.sections
    # Shows sections expanded by default
    - navigation.expand
    # Enables annotations in code blocks
    - content.code.annotate
  # logo: assets/logo.svg
  # favicon: images/favicon-platform.svg

repo_name: uTu-agent
repo_url: https://github.com/utu-agent/utu-agent

extra:
  # Remove material generation message in footer
  generator: false
  language: en

plugins: 
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["utu"]
          selection:
            docstring_style: google
          options:
            # Shows links to other members in signatures
            signature_crossrefs: true
            # Orders members by source order, rather than alphabetical
            members_order: source
            # Puts the signature on a separate line from the member name
            separate_signature: true
            # Shows type annotations in signatures
            show_signature_annotations: true
            # Makes the font sizes nicer
            heading_level: 3
            # Show inherited members
            inherited_members: true
            # show_root_heading: true
            show_source: true

watch:
  - utu

nav:
  - Intro: index.md
  - Quickstart: quickstart.md
  - Examples: examples.md
  - API Reference:
    - ref/simple_agent.md
    - Tools:
      - ref/tool/base_toolkit.md
      - ref/tool/document_toolkit.md
      - ref/tool/image_toolkit.md
      - ref/tool/search_toolkit.md
      - ref/tool/video_toolkit.md

