[project]
name = "utu-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "arize-phoenix-otel>=0.11.0",
    "arxiv>=2.2.0",
    "chunkr-ai>=0.1.0",
    "hydra-core>=1.3.2",
    "jinja2>=3.1.6",
    "mcp>=1.9.4",
    "openai-agents>=0.1.0",
    "openinference-instrumentation-openai>=0.1.30",
    "openinference-instrumentation-openai-agents>=0.1.14",
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "pexpect>=4.9.0",
    "pillow>=11.2.1",
    "psycopg2-binary>=2.9.10",
    "sqlmodel>=0.0.24",
    "tiktoken>=0.9.0",
    "toml>=0.10.2",
    "wikipedia-api>=0.8.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["utu"]


[tool.pytest.ini_options]
pythonpath = "."
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
addopts = "-v -s"
log_cli = true
log_cli_level = "INFO"

[tool.uv]
index-url = "https://pypi.org/simple"
extra-index-url = [
    "https://mirrors.tencent.com/repository/pypi/tencent_pypi/simple",
]
