# @package _global_
defaults:
  - /model/base@model
  - /tools/search@toolkits.search
  - /tools/document@toolkits.document
  - /tools/python_executor@toolkits.python_executor
  - _self_

agent:
  name: data_analysis_agent
  instructions: "You are a helpful assistant."

