dataset: "data/utu_test/agent_test.jsonl"
# eval_method: "BrowseComp"
type: "mixed"
question_field: "question"
gt_field: "answer"

output_file: "predict_results_8.jsonl"
metrics_file : "eval_metrics.json"
judge_output_file: "judge_results.jsonl"

thread_pool_size: 8
concurrency: 8
max_turns: 12

judge_model: ${oc.env:JUDGE_MODEL}
judge_api_key: ${oc.env:JUDGE_API_KEY}
judge_model_base_url: ${oc.env:JUDGE_MODEL_BASE_URL}
judge_concurrency: 8
judge_max_tokens: 4096
