# @package _global_
defaults:
  - /agents/exp/v03@agent
  - /eval/data/mixed@data
  - _self_

exp_id: "v0.3"

concurrency: 16

judge_model: ${oc.env:JUDGE_MODEL}
judge_api_key: ${oc.env:JUDGE_API_KEY}
judge_model_base_url: ${oc.env:JUDGE_MODEL_BASE_URL}
judge_concurrency: 16
judge_max_tokens: 4096
