# @package _global_
defaults:
  - /agents/exp/v01@agent
  - _self_

exp_id: "v0.1_GAIA_val"

dataset: "GAIA_val"
type: "single"
question_field: "Question"
gt_field: "Final answer"

concurrency: 8

judge_model: ${oc.env:JUDGE_MODEL}
judge_api_key: ${oc.env:JUDGE_API_KEY}
judge_model_base_url: ${oc.env:JUDGE_MODEL_BASE_URL}
judge_concurrency: 8
judge_max_tokens: 4096
