# @package _global_
defaults:
  - /agents/v01@agent
  - _self_

exp_id: "v0.1"

dataset: "data/utu_test/agent_test.jsonl"
# eval_method: "BrowseComp"
type: "mixed"
question_field: "question"
gt_field: "answer"

output_file: "predict_results.jsonl"
metrics_file : "eval_metrics.json"
judge_output_file: "judge_results.jsonl"

concurrency: 8
max_turns: 12

judge_model: ${oc.env:JUDGE_MODEL}
judge_api_key: ${oc.env:JUDGE_API_KEY}
judge_model_base_url: ${oc.env:JUDGE_MODEL_BASE_URL}
judge_concurrency: 8
judge_max_tokens: 4096