# @package _global_
defaults:
  - /agents/exp/v03@agent
  - _self_

exp_id: "v0.3"

dataset: "data/utu_test/agent_test_webwalker.jsonl"
type: "mixed"
question_field: "question"
gt_field: "answer"

concurrency: 8
max_turns: 12

judge_model: ${oc.env:JUDGE_MODEL}
judge_api_key: ${oc.env:JUDGE_API_KEY}
judge_model_base_url: ${oc.env:JUDGE_MODEL_BASE_URL}
judge_concurrency: 8
judge_max_tokens: 4096
