name: audio
mode: builtin
activated_tools: null
config:
  audio_model:
    model: whisper-1
    api_key: "${oc.env:AUDIO_API_KEY}"
    base_url: "${oc.env:AUDIO_BASE_URL}"
config_llm:
  model: "${oc.env:UTU_TOOL_MODEL}"
  api_key: "${oc.env:UTU_API_KEY}"
  base_url: "${oc.env:UTU_BASE_URL}"
