name: document
mode: builtin
activated_tools: null
config: {
  "high_resolution": true,
}
config_llm:
  model: "${oc.env:UTU_TOOL_DOCUMENT_MODEL}"
  api_key: "${oc.env:UTU_API_KEY}"
  base_url: "${oc.env:UTU_BASE_URL}"
  