name: search
mode: builtin
activated_tools: null
config:
  summary_token_limit: 10_000
  SERPER_API_KEY: ${oc.env:SERPER_API_KEY}
  JINA_API_KEY: ${oc.env:JINA_API_KEY}
config_llm:
  model: "${oc.env:UTU_TOOL_MODEL}"
  api_key: "${oc.env:UTU_API_KEY}"
  base_url: "${oc.env:UTU_BASE_URL}"