agent:
    name: utu-default
    instructions: "You are a helpful assistant."

model:
    api_key: ${oc.env:UTU_API_KEY}
    base_url: ${oc.env:UTU_BASE_URL}
    model: ${oc.env:UTU_MODEL}

toolkits:
    - name: search
      mode: builtin
      activated_tools: null
      config: null
